[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

surrealdb = { version = "1.0.0-beta.9+20230402" }
tokio = { version = "1.28.1", features = ["full", "macros", "rt-multi-thread"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
