[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
# tarpc
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }
log = "0.4.19"
futures = "0.3.28"
opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.18.0", features = ["rt-tokio"] }
rand = "0.8.5"
tarpc = { version = "0.33.0", features = ["full"] }
tokio = { version = "1.28.2", features = ["macros", "net", "rt-multi-thread"] }
tracing = { version = "0.1.37" }
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# my db
redb = { version = "0.22.0  " }
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.96" }
sqlite = { version = "0.30.4" }

[lib]
name = "service"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
