[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.4", features = ["sqlite", "chrono", "returning_clauses_for_sqlite_3_35", "r2d2"] }
uuid = { version = "1.3.2", features = ["v4"] }
bytes = "1.4.0"

color-eyre = "0.6.2"
chrono = { version = "0.4.24" }
clap = { version = "4.2.7", features = ["derive"] }

diesel-derive-enum = { version = "2.0.1", features = ["sqlite"] }
tonic = "0.9.2"
prost = "0.11.9"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.28"
rand = "0.8.5"
anyhow = "1.0.71"

serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
dotenvy = "0.15.7"
redb = "0.21.0"

[build-dependencies]
tonic-build = "0.9.2"
